version: '3.8'

networks:
  default:

services:
  db:
    image: postgres
    container_name: exam
    restart: always
    ports:
      - 25432:5432
    volumes:
      - "./.data/db:/var/lib/postgres/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exam